spring:
  application:
    name: apigw
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id : customer
          uri: lb://CUSTOMER
          predicates:
            - Path= /api/v1/customer/**

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
